INSERT INTO book (id, name, author, publisher, year_released, version) VALUES
(1, 'The Hobbit', 'J.R.R. Tolkien', 'George Allen & Unwin', 1937, 0),
(2, '1984', 'George Orwell', 'Secker & Warburg', 1949, 0),
(3, 'To Kill a Mockingbird', 'Harper Lee', 'J.B. Lippincott & Co.', 1960, 0),
(4, 'Pride and Prejudice', 'Jane Austen', 'T. Egerton', 1813, 0),
(5, 'The Catcher in the Rye', 'J.D. Salinger', 'Little, Brown and Company', 1951, 0),
(6, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Charles Scribner’s Sons', 1925, 0),
(7, 'Moby Dick', 'Herman Melville', 'Harper & Brothers', 1851, 0),
(8, 'War and Peace', 'Leo Tolstoy', 'The Russian Messenger', 1869, 0),
(9, 'Brave New World', 'Aldous Huxley', 'Chatto & Windus', 1932, 0),
(10, 'The Lord of the Rings', 'J.R.R. Tolkien', 'Allen & Unwin', 1954, 0),
(11, 'The Alchemist', 'Paulo Coelho', 'HarperTorch', 1988, 0),
(12, 'The Da Vinci Code', 'Dan Brown', 'Doubleday', 2003, 0),
(13, 'Harry Potter and the Philosopher’s Stone', 'J.K. Rowling', 'Bloomsbury', 1997, 0),
(14, 'The Shining', 'Stephen King', 'Doubleday', 1977, 0),
(15, 'Crime and Punishment', 'Fyodor Dostoevsky', 'The Russian Messenger', 1866, 0),
(16, 'Jane Eyre', 'Charlotte Brontë', 'Smith, Elder & Co.', 1847, 0),
(17, 'Wuthering Heights', 'Emily Brontë', 'Thomas Cautley Newby', 1847, 0),
(18, 'The Book Thief', 'Markus Zusak', 'Picador', 2005, 0),
(19, 'The Kite Runner', 'Khaled Hosseini', 'Riverhead Books', 2003, 0),
(20, 'Sapiens', 'Yuval Noah Harari', 'Harvill Secker', 2011, 0),
(21, 'Thinking, Fast and Slow', 'Daniel Kahneman', 'Farrar, Straus and Giroux', 2011, 0),
(22, 'The Power of Habit', 'Charles Duhigg', 'Random House', 2012, 0),
(23, 'Atomic Habits', 'James Clear', 'Penguin Random House', 2018, 0),
(24, 'Deep Work', 'Cal Newport', 'Grand Central Publishing', 2016, 0),
(25, 'The Lean Startup', 'Eric Ries', 'Crown Business', 2011, 0),

(26, 'A Tale of Two Cities', 'Charles Dickens', 'Chapman & Hall', 1859, 0),
(27, 'Les Misérables', 'Victor Hugo', 'A. Lacroix, Verboeckhoven & Cie.', 1862, 0),
(28, 'The Picture of Dorian Gray', 'Oscar Wilde', 'Ward, Lock & Co.', 1890, 0),
(29, 'Dracula', 'Bram Stoker', 'Archibald Constable and Company', 1897, 0),
(30, 'Frankenstein', 'Mary Shelley', 'Lackington, Hughes, Harding, Mavor & Jones', 1818, 0),
(31, 'The Count of Monte Cristo', 'Alexandre Dumas', 'Penguin Classics', 1844, 0),
(32, 'Don Quixote', 'Miguel de Cervantes', 'Francisco de Robles', 1605, 0),
(33, 'The Brothers Karamazov', 'Fyodor Dostoevsky', 'The Russian Messenger', 1880, 0),
(34, 'The Stranger', 'Albert Camus', 'Gallimard', 1942, 0),
(35, 'The Trial', 'Franz Kafka', 'Verlag Die Schmiede', 1925, 0),
(36, 'One Hundred Years of Solitude', 'Gabriel García Márquez', 'Harper & Row', 1967, 0),
(37, 'Love in the Time of Cholera', 'Gabriel García Márquez', 'Alfred A. Knopf', 1985, 0),
(38, 'Midnight’s Children', 'Salman Rushdie', 'Jonathan Cape', 1981, 0),
(39, 'Beloved', 'Toni Morrison', 'Alfred A. Knopf', 1987, 0),
(40, 'Invisible Man', 'Ralph Ellison', 'Random House', 1952, 0),
(41, 'The Sun Also Rises', 'Ernest Hemingway', 'Scribner', 1926, 0),
(42, 'Of Mice and Men', 'John Steinbeck', 'Covici Friede', 1937, 0),
(43, 'The Grapes of Wrath', 'John Steinbeck', 'The Viking Press-James Lloyd', 1939, 0),
(44, 'Slaughterhouse-Five', 'Kurt Vonnegut', 'Delacorte', 1969, 0),
(45, 'Catch-22', 'Joseph Heller', 'Simon & Schuster', 1961, 0),
(46, 'On the Road', 'Jack Kerouac', 'Viking Press', 1957, 0),
(47, 'The Bell Jar', 'Sylvia Plath', 'Heinemann', 1963, 0),
(48, 'Fahrenheit 451', 'Ray Bradbury', 'Ballantine Books', 1953, 0),
(49, 'The Road', 'Cormac McCarthy', 'Alfred A. Knopf', 2006, 0),
(50, 'A Clockwork Orange', 'Anthony Burgess', 'William Heinemann', 1962, 0);

ALTER TABLE book ALTER COLUMN id RESTART WITH 51;